#!/usr/bin/env python3
"""Copy the grammar material this site quotes, verbatim, out of the code repo.

    python3 scripts/sync-grammar.py [path-to-thamizh-mcp]

Why a script and not copy-paste: the design repo's standing rule is that a நூற்பா is
quoted programmatically and never retyped, because a transcription drifts within minutes
of being read and the drift is invisible. Every Tamil string in src/data/grammar.json
therefore arrives here by machine, from data/grammar/*.json in the code repo, which are
themselves checked against the pinned Project Madurai editions by its test suite.

If the code repo is not checked out beside this one, the script exits without touching
anything, so a CI build never depends on it.
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_CODE_REPO = HERE.parent / "thamizh-mcp"


def main() -> int:
    code = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CODE_REPO
    grammar = code / "data" / "grammar"
    if not grammar.is_dir():
        print(f"thamizh-mcp not found at {code}; leaving src/data/grammar.json alone.")
        return 0

    cases = json.loads((grammar / "verrumai_urubu.json").read_text(encoding="utf-8"))
    concepts = json.loads((grammar / "concept_map.json").read_text(encoding="utf-8"))

    out = {
        "_comment": (
            "Generated by scripts/sync-grammar.py from thamizh-mcp/data/grammar/. "
            "Do not edit by hand: every Tamil string here is quoted from the pinned "
            "classical editions and must arrive by machine."
        ),
        "synced_on": "2026-08-19",
        "source": "https://github.com/ief-global/thamizh-mcp/tree/main/data/grammar",
        "attribution": concepts["attribution"],
        "source_priority": cases["source_priority"],
        # The seventh case, because it is the one மரத்தில் lands in, and the third,
        # because it is where the two authorities genuinely disagree.
        "case_locative": cases["cases"]["loc"],
        "case_instrumental": cases["cases"]["inst"],
        "known_gaps": cases["known_gaps"],
        # நன்னூல் 133 names all six பகுபத உறுப்பு. It is the verse the whole
        # morphology page rests on.
        "six_parts_verse": concepts["concepts"]["பகுபதம் / பகாப்பதம்"]["stated"][0],
        # The six உறுப்பு themselves, with the English name the project uses for each.
        "six_parts": [
            {"tamil": name, "english": concepts["concepts"][name]["english"]}
            for name in ("பகுதி", "விகுதி", "இடைநிலை", "சாரியை", "சந்தி", "விகாரம்")
        ],
        # What the project treats as derived rather than stated, and still open.
        "inferred_vikaram": concepts["concepts"]["விகாரம்"]["inferred"][0]["claim"],
        "open_review": concepts["open_review_list"],
        "how_to_use": concepts["how_to_use"],
    }
    dest = HERE / "src" / "data" / "grammar.json"
    dest.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {dest.relative_to(HERE)} from {grammar}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
