#!/usr/bin/env python3
"""Copy the glossary's quick-reference table out of the design repo.

    python3 scripts/sync-glossary.py [path-to-thamizh-mcp-design]

Glossary.md maps computational-linguistics vocabulary onto Tamil grammar terms, for
scholars who know வேற்றுமை and விகுதி but have no reason to know "lemma" or "FST". It is
the design repo's document and stays so; this copies the summary table verbatim rather
than paraphrasing it into a second, drifting version.

Exits without touching anything if the design repo is not checked out beside this one.
"""
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_DESIGN_REPO = HERE.parent / "thamizh-mcp-design"


def main() -> int:
    design = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DESIGN_REPO
    src = design / "Glossary.md"
    if not src.is_file():
        print(f"thamizh-mcp-design not found at {design}; leaving src/data/glossary.json alone.")
        return 0

    text = src.read_text(encoding="utf-8")
    section = text.split("## Quick reference", 1)[1].split("\n---", 1)[0]
    rows = []
    for line in section.splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 3 or cells[0].startswith("---") or cells[0] == "Technical term":
            continue
        rows.append({"term": cells[0], "tamil": cells[1], "gloss": cells[2]})

    dest = HERE / "src" / "data" / "glossary.json"
    dest.write_text(
        json.dumps(
            {
                "_comment": "Generated by scripts/sync-glossary.py from thamizh-mcp-design/Glossary.md. Do not edit by hand.",
                "synced_on": "2026-08-19",
                "source": "https://github.com/ief-global/thamizh-mcp-design/blob/main/Glossary.md",
                "rows": rows,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {dest.relative_to(HERE)} — {len(rows)} terms")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
