#!/usr/bin/env python3
"""Copy the source registry out of the code repo, so the ledger cannot drift.

    python3 scripts/sync-sources.py [path-to-thamizh-mcp]

thamizh-mcp/data/sources.json (D-017) is the machine-readable record of every grounding
source: its evidential GRADE and its legal REDISTRIBUTION MODE, kept as independent axes.
The site renders that file rather than a retelling of it, so a grade cannot be flattering
here and honest there.

Exits without touching anything if the code repo is not checked out beside this one.
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_CODE_REPO = HERE.parent / "thamizh-mcp"

# Fields the site shows. Adapter paths and internal call sites stay out: they change often
# and mean nothing to a reader who is not in the code.
KEEP = (
    "name", "authority", "tier", "grade", "licence", "licence_status", "redistribution",
    "attribution", "pin", "maintenance", "notes", "adapter_status", "supersession",
)


def main() -> int:
    code = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CODE_REPO
    registry = code / "data" / "sources.json"
    if not registry.is_file():
        print(f"thamizh-mcp not found at {code}; leaving src/data/sources.json alone.")
        return 0

    reg = json.loads(registry.read_text(encoding="utf-8"))
    out = {
        "_comment": (
            "Generated by scripts/sync-sources.py from thamizh-mcp/data/sources.json. "
            "Do not edit by hand."
        ),
        "synced_on": "2026-08-19",
        "registry_updated": reg["updated"],
        "source": "https://github.com/ief-global/thamizh-mcp/blob/main/data/sources.json",
        "grades": {k: v for k, v in reg["grades"].items() if k in ("A", "B", "C", "D")},
        "redistribution_modes": {
            k: v for k, v in reg["redistribution_modes"].items() if k != "comment"
        },
        "sources": {
            key: {f: entry[f] for f in KEEP if f in entry}
            for key, entry in reg["sources"].items()
        },
    }
    dest = HERE / "src" / "data" / "sources.json"
    dest.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {dest.relative_to(HERE)} — {len(out['sources'])} sources")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
